### ISSUE TITLE
Use event aggregation to provide animation events

### ISSUE THREAD

**Issue by zewa666** [aurelia/animator-css#13]
An opt-in feature could be to trigger events on certain situations during animations. The first pass should just retrigger the original catched ones.

Lets see if we find more use cases around this.

**Comment by zewa666** [comment]
@EisenbergEffect Would you solve that using the EventAggregator or with Custom Events? I'm not sure whether adding a dependency to the EA Repo is going to introduce additional weight

**Comment by EisenbergEffect** [comment]
I would use DOM events.

**Comment by zewa666** [comment]
I'm just wondering how we can provide a known list of events, so that all Animator have the same set. Guess the easiest would be to include a pseudo-enum as class within the BaseAnimator, which then may be used by the concrete implementation?

Here's my recommended set of events:
* animation:enter:begin
* animation:enter:active
* animation:enter:done
* animation:enter:timeout
* ---
* animation:leave:begin
* animation:leave:active
* animation:leave:done
* animation:leave:timeout
* ---
* animation:stagger:next
* ---
* animation:remove-class:begin
* animation:remove-class:done
* animation:remove-class:timeout
* ---
* animation:add-class:begin
* animation:add-class:done
* animation:add-class:timeout

**Comment by EisenbergEffect** [comment]
Yes, we could just create an enum, something similar to how the bindingModes works, for example. That can exist inside of the templating repo.

As to the events themselves, I look to you for that, since you've worked more with the animation than I have.
