### ISSUE TITLE
TypeScript Definition error

### ISSUE THREAD

**Issue by KarlDirck** [aurelia/animator-css#27]
For release 'animator-css@0.15.0', the aurelia-animator-css.d.ts file includes the following on line 28:
`    runSequence(animations: Array<CssAnimation>): Promise<boolean>;`
which results in a TS error:
`aurelia-animator-css.d.ts(28,35): error TS2304: Cannot find name 'CssAnimation'.`

**Comment by zewa666** [comment]
@cmichaelgraham can you help out with this one?

**Comment by EisenbergEffect** [comment]
I can fix it. The interface isn't making it into the build. Easiest thing to do would be to move it into one of the other files.

**Comment by zewa666** [comment]
Sure yes please go ahead. Anyway it would be interesting to know how we can use separate files which contain the interface, in case other modules got more of them.

**Comment by EisenbergEffect** [comment]
This is fixed and going out in the next release tomorrow.
