### ISSUE TITLE
Animation throws error when using external css

### ISSUE THREAD

**Issue by kdeberni** [aurelia/animator-css#39]
We just moved to beta version and I think there is a bug in animator.js in method _animationChangeWithValidKeyframe when using external css.
In line 156 is an itterator through cssRules of a styleSheet. However styleSheet from external css have null in cssRule property so an error is thrown on code 'cssRules.length'.
Or I am missing something?

**Comment by zewa666** [comment]
@kdeberni good catch, fix is checked into master and will be rolled out with the next release

**Comment by kdeberni** [comment]
@zewa666 Thanks for the info. By the way animation now works superb :-). Realy like the job you have done.

**Comment by EisenbergEffect** [comment]
Ok, I'll close this issue. @zewa666 If it looks good to you, I can do a patch release. Let me know and I'll get it out.

**Comment by zewa666** [comment]
@EisenbergEffect oki doki ready for release :+1:
