### ISSUE TITLE
Firefox throws "SecurityError" exception

### ISSUE THREAD

**Issue by kdeberni** [aurelia/animator-css#40]
This is actualy connected with issue #39 (external css).
I found out that usage of cssRules of an external styleSheet in Firefox throws "SecurityError" exception. This is the the case in line 154 of animator.js. 
The only working "fix" I found is to wrap access to cssRules with try/catch.

**Comment by EisenbergEffect** [comment]
@zewa666 Can you look into this?

**Comment by zewa666** [comment]
@EisenbergEffect not sure how important this one is, but maybe we can wait for a fix for the other issue regarding the list that Martin is working on and release those then together.

**Comment by EisenbergEffect** [comment]
I think it can wait for now.
