### ISSUE TITLE
Animation for new view is completely finished before animation for old view starts

### ISSUE THREAD

**Issue by DamageLimiter** [aurelia/animator-css#41]
I am not quite sure if it's intended like this as default behaviour. But right now what happens is, that on navigation the new view animation finishes completely before it starts with the animation of the old view. But what if I'd like to have my old view disappeared before the new one starts to "slide" in?

In my current scenario I want to have my current view animated with `fadeOutLeft` and my new view animated with `fadeInRight`. What happens is, that new view is faded in from right beneath my current view, then my current view is faded out to the left. Once it's gone the new view jumps to the top.

**Comment by DamageLimiter** [comment]
Apologies. It's not a bug. It's my fault. I wasn't aware of "swap-order".
`swap-order="after"`fixed the problem. Sorry for any inconvenience caused.

**Comment by EisenbergEffect** [comment]
If you update, I believe that swap-order="after" is now the default.

**Comment by DamageLimiter** [comment]
Yes, you are correct. I messed with my router-view a couple of weeks ago. I had `swap-order="before"` defined and `show.bind="!router.isNavigating"`. I didn't even remember doing this :-P
I've created a trap, forgot about it and jumped right into it.

**Comment by EisenbergEffect** [comment]
LOL Glad it's all fixed :)
