### ISSUE TITLE
Animations issue in firefox

### ISSUE THREAD

**Issue by lares83** [aurelia/animator-css#42]
Hi,
I've prepared code on plunker:
http://plnkr.co/edit/00Rq7W?p=preview

As you can see list animation works fine in Chrome and Edge but in Firefox it doesn't.

**Comment by zewa666** [comment]
this is more an issue with css. Firefox seems to have an issue setting `opacity:0 !important`. Your activation hooks also contained only standard + webkit prefixes but no -moz prefixes.

Take a look at the updated plunkr here

http://plnkr.co/edit/e6t6WGUBaQtX1Egj5qMY?p=preview

**Comment by lares83** [comment]
Yes now it's working fine. It was due to `opacity:0 !important`. As far as I know Firefox right now doesn't need -moz prefixes, so removing `important` fixed issue.

I took all those styles from aurelia blog
http://blog.durandal.io/2015/07/17/animating-apps-with-aurelia-part-1/

Maybe it would be good to upgrade this post for others. 
Could you also add some article about animations in aurelia docs? It would be nice to have it there:)

Thanks for you help:)

**Comment by EisenbergEffect** [comment]
@zewa666 Do we need to update the source in the skeletons? If so, can you submit a PR for that?
