### ISSUE TITLE
Last item does not animate

### ISSUE THREAD

**Issue by hadrienl** [aurelia/animator-css#49]
Hi,

I'm trying to make aurelia-css-animate to work but I have some problems. I've followed @EisenbergEffect  post and I finally have something which seems to work :

![mai-30-2016 10-23-04](https://cloud.githubusercontent.com/assets/225382/15644044/def1247a-2650-11e6-979b-774db91f3990.gif)

But not for the last item. Last item does not animate at all.

Then, if I add the `au-stagger` class to my ul, when removing the last li (which does not animated) I have the following error :

`aurelia-templating.js:1372 Uncaught (in promise) TypeError: Cannot read property 'returnToCache' of undefined``

![capture d ecran 2016-05-30 10 24 16](https://cloud.githubusercontent.com/assets/225382/15644078/0fbb5f80-2651-11e6-93ac-ccf95557bf12.png)

**Comment by hadrienl** [comment]
AH AH AH ! I've found my mistake… so stupid…

I had a if.bind on my ul :

```
<ul
  if.bind="items.length">
  <li
    repeat.for="item of items">[…]</li>
</ul>
```

Don't make the same -_-

**Comment by zewa666** [comment]
haha ok. Guess we can close this one right? Lets reopen if you still encounter an issue
