### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by mradzinski** [aurelia/animator-css#51]
Consider updating the .d.ts file and change all HTMLElement classes to Element. Had to do this manually for aurelia-css-animator to work with Typescript.

**Comment by EisenbergEffect** [comment]
Would you be interested in submitting a PR with the fix? The type changes can be made directly in the source code. We use Babel Flow types to convert to TypeScript dts files.

**Comment by ne0guille** [comment]
can you update yout d.ts file? would be a time saver thanks!

**Comment by zewa666** [comment]
@ne0guille, @mradzinski you're right guys sorry for the oversight and for it taking so long. Will be fixed with the next release

**Comment by zewa666** [comment]
ok the release is out, please give it a try and reply here if somethings still not working as expected
