### ISSUE TITLE
Infinite scrolling animation delays accumulate

### ISSUE THREAD

**Issue by liamdawson** [aurelia/animator-css#55]
**I'm submitting a bug report**
- **Library Version:**
  1.0.1

**Please tell us about your environment:**
- **Operating System:**
  Linux (Debian Jessie)
- **Node Version:**
  4.5.0
  
  
- **NPM Version:**
  3.10.6
  
  
- **Build Tooling:**
  Using Aurelia CLI version 0.18.0
- **Browser:**
  Chrome 53
- **Language:**
  ESNext

**Steps:**
- Have a list with `au-stagger` with a 0.2s transition delay
- Add 1000 animated items
- Wait for animations to complete
- Add 1000 more animated items
- **What is the expected behavior?**
- First new animated item immediately begins animation
- **What is the actual behavior?**
- First new animated item waits for 1000 \* 0.2s before it begins animation
- **What is the motivation / use case for changing the behavior?**
- Infinite scrolling - otherwise there are longer and longer unnecessary delays as you scroll

**Comment by liamdawson** [comment]
Culprit: https://github.com/aurelia/animator-css/blob/master/src/animator.js#L324

If you have any quick pointers on how to fix this, I'll happily do and PR.

**Comment by EisenbergEffect** [comment]
@zewa666 Do you have any thoughts on this?

**Comment by z-brooks** [comment]
@zewa666 @EisenbergEffect https://github.com/aurelia/animator-css/pull/60
I didn't see a way get how many elements are changing state (enter/leave) so I've stored the currently active count in the stagger parent to use as the delay multiplier. Acceptable?

**Comment by zewa666** [comment]
@z-brooks, @liamdawson please give it a try with the new release
