### ISSUE TITLE
Throw an error that is view.bindingContext is null when use au-stagger with if.bind and push item to empty array

### ISSUE THREAD

**Issue by alu** [aurelia/animator-css#57]
**I'm submitting a bug report**

* **Library Version:**
1.0.1

**Please tell us about your environment:**
* **Operating System:**
Linux (fedora 23)

* **Node Version:**
7.4.0

* **NPM Version:**
4.0.5

* **JSPM OR Webpack AND Version**
webpack 1.14.0

* **Browser:**
Firefox 50.1.0

* **Language:**
typescript 2.1.5

**Current behavior:**

Throw an error that is ` view.bindingContext is null` when use `au-stagger` with `if.bind` and push item to empty array. The sample is below.

test.html
```html
<template>
  <ul class="au-stagger some-animation-class" if.bind="items.length > 0">
    <li class="au-animate" repeat.for="item of items">${item}</li>
  </ul>
</template>
```

test.ts
```ts
export default class {
  private items = ['a', 'b', 'c'];

  attached() {
    setInterval(_ => {
      if (this.items.length > 0) {
        // 1. every secs splice an item to array (this code is not important, just for create empty array)
        this.items.splice(this.items.length - 1, 1);
      } else {
       // 2. if the array is empty, push to new item. and then, an error occur "view.bindingContext is null"
        this.items.push('pushed!!');
      }
    }, 3000);
  }
}
```

**Comment by zewa666** [comment]
@alu actually I got a different error for your example. Its root is in the templating repo, but I've queued a PR for a fix.
