### ISSUE TITLE
Animation Timeout Removes Classes Before Animation Start

### ISSUE THREAD

**Issue by andrewmunsell** [aurelia/animator-css#6]
Because the plugin tries to remove the `au-{event}` and `au-{event}-active` classes after 50ms if the animation has not started, I am running into an issue where the classes are removed before the `animationstart` event ever fires.

I changed the timeout value from 50ms to 100ms and the issue was fixed in Chrome.

Also, this might present an issue if the `animationstart` event is only fired after the `animation-delay` period has finished (per https://developer.mozilla.org/en-US/docs/Web/Events/animationstart). This means that all animations *must* have a delay of less than whatever the defined timeout period is.

**Comment by zewa666** [comment]
Hi there, thanks for the feedback. Could you tell me the scenario where you had those timing issues? Was it inside a repeater or on normal elements? I've been able to sometimes see the behavior on the repeater, but not in a reproducible way so I'd be glad to hear about your try.

Regarding the animation-delay, I was going to add more logic to the implementation, checking whether the classes do use an animation-delay. That should fix this issue.

**Comment by andrewmunsell** [comment]
The issue was actually in a top level `router-view`-- there wasn't any nesting or anything really complicated. This is a somewhat larger application (it's definitely not just the skeleton navigation), but still what I'd expect is considered a normal use case.

I was running this on a mid-2012 Macbook Air.

Basic structure of the app to give you an idea where it is, though this is greatly simplified from the actual application:

```
<html>
    <body>
        <custom-element>
        <router-view>
    </body>
</html

**Comment by zewa666** [comment]
@andrewmunsell sry that it took me so long, but I think the latest release now fixes as well the not triggering of animations (essentially just increased the delay as you suggested) and respects a set animation delay.
