### ISSUE TITLE
Animation not working IE11

### ISSUE THREAD

**Issue by mtimms** [aurelia/animator-css#8]
The animation effect on Skeleton.013 works on Chrome but has no effect in IE11.

**Comment by EisenbergEffect** [comment]
@zewa666 Can you take a look at this please?

**Comment by zewa666** [comment]
Seems to be related to ViewSlot handling https://github.com/aurelia/templating/blob/master/src/view-slot.js#L202, might got introduced with the latest batch of changes. We'll get that fixed
